"""esquema inicial

Revision ID: 161f682239e7
Revises: 
Create Date: 2026-08-03 00:17:24.459009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161f682239e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_entidad', sa.String(), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('campo', sa.String(), nullable=True),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_id'), 'historial', ['id'], unique=False)
    op.create_table('mantenimientos_preventivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_realizada', sa.DateTime(), nullable=True),
    sa.Column('tecnico_asignado', sa.String(), nullable=True),
    sa.Column('actividades_realizadas', sa.String(), nullable=True),
    sa.Column('repuestos_utilizados', sa.String(), nullable=True),
    sa.Column('contador_bn', sa.Integer(), nullable=True),
    sa.Column('contador_color', sa.Integer(), nullable=True),
    sa.Column('frecuencia_preventivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_preventivos_id'), 'mantenimientos_preventivos', ['id'], unique=False)
    op.drop_index(op.f('ix_modelos_id'), table_name='modelos')
    op.drop_table('modelos')
    op.drop_index(op.f('ix_impuestos_id'), table_name='impuestos')
    op.drop_table('impuestos')
    op.drop_index(op.f('ix_mano_obra_id'), table_name='mano_obra')
    op.drop_table('mano_obra')
    op.drop_index(op.f('ix_mantenimiento_preventivo_id'), table_name='mantenimiento_preventivo')
    op.drop_table('mantenimiento_preventivo')
    op.drop_index(op.f('ix_mantenimiento_correctivo_id'), table_name='mantenimiento_correctivo')
    op.drop_table('mantenimiento_correctivo')
    op.drop_index(op.f('ix_valor_facturado_id'), table_name='valor_facturado')
    op.drop_table('valor_facturado')
    op.drop_index(op.f('ix_polizas_id'), table_name='polizas')
    op.drop_table('polizas')
    op.add_column('contratos', sa.Column('poliza_contrato', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('poliza_seriedad', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('equipo_id', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('mantenimiento', sa.Enum('PREVENTIVO', 'CORRECTIVO', name='tipomantenimiento'), nullable=False))
    op.add_column('contratos', sa.Column('valor_mensual_base', sa.Float(), nullable=True))
    op.add_column('contratos', sa.Column('paginas_bn_incluidas', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('paginas_color_incluidas', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('valor_pagina_adicional_bn', sa.Float(), nullable=True))
    op.add_column('contratos', sa.Column('valor_pagina_adicional_color', sa.Float(), nullable=True))
    op.add_column('contratos', sa.Column('escaneos_incluidos', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('valor_escaneo_adicional', sa.Float(), nullable=True))
    op.drop_column('contratos', 'seriedad')
    op.add_column('equipos', sa.Column('contador_inicial_bn', sa.Integer(), nullable=True))
    op.add_column('equipos', sa.Column('contador_inicial_color', sa.Integer(), nullable=True))
    op.add_column('equipos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('equipos', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('facturacion', sa.Column('multiempresa', sa.Enum('CONTINENTAL_LTDA', 'OTRA', name='empresafacturadora'), nullable=True))
    op.add_column('facturacion', sa.Column('es_multiempresa', sa.Boolean(), nullable=True))
    op.drop_column('insumos', 'toner')
    op.drop_column('insumos', 'tipo_insumo')
    op.add_column('lecturas', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('lecturas', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('lecturas', sa.Column('periodo', sa.String(), nullable=True))
    op.add_column('lecturas', sa.Column('contador_bn', sa.Integer(), nullable=True))
    op.add_column('lecturas', sa.Column('contador_color', sa.Integer(), nullable=True))
    op.drop_column('lecturas', 'contador')
    op.add_column('rentabilidad', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('rentabilidad', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('servicios', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('servicios', sa.Column('equipo_id', sa.Integer(), nullable=True))
    op.add_column('servicios', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('servicios', sa.Column('fecha_solicitud', sa.DateTime(), nullable=True))
    op.add_column('servicios', sa.Column('falla_reportada', sa.String(), nullable=True))
    op.add_column('servicios', sa.Column('prioridad', sa.String(), nullable=True))
    op.add_column('servicios', sa.Column('fecha_atencion', sa.DateTime(), nullable=True))
    op.add_column('servicios', sa.Column('fecha_solucion', sa.DateTime(), nullable=True))
    op.add_column('servicios', sa.Column('diagnostico', sa.String(), nullable=True))
    op.add_column('servicios', sa.Column('costo_repuestos', sa.Float(), nullable=True))
    op.add_column('servicios', sa.Column('costo_mano_obra', sa.Float(), nullable=True))
    op.add_column('servicios', sa.Column('costo_desplazamiento', sa.Float(), nullable=True))
    op.add_column('servicios', sa.Column('requiere_respaldo', sa.String(), nullable=True))
    op.add_column('servicios', sa.Column('estado_caso', sa.String(), nullable=True))
    op.alter_column('servicios', 'mantenimiento',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('tipos_insumo', sa.Column('stock_minimo', sa.Float(), nullable=True))
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'estado_aprobacion',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'),
               existing_nullable=True,
               existing_server_default=sa.text("'APROBADO'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'estado_aprobacion',
               existing_type=sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'APROBADO'"))
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tipos_insumo', 'stock_minimo')
    op.alter_column('servicios', 'mantenimiento',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('servicios', 'estado_caso')
    op.drop_column('servicios', 'requiere_respaldo')
    op.drop_column('servicios', 'costo_desplazamiento')
    op.drop_column('servicios', 'costo_mano_obra')
    op.drop_column('servicios', 'costo_repuestos')
    op.drop_column('servicios', 'diagnostico')
    op.drop_column('servicios', 'fecha_solucion')
    op.drop_column('servicios', 'fecha_atencion')
    op.drop_column('servicios', 'prioridad')
    op.drop_column('servicios', 'falla_reportada')
    op.drop_column('servicios', 'fecha_solicitud')
    op.drop_column('servicios', 'contrato_id')
    op.drop_column('servicios', 'equipo_id')
    op.drop_column('servicios', 'cliente_id')
    op.drop_column('rentabilidad', 'cliente_id')
    op.drop_column('rentabilidad', 'contrato_id')
    op.add_column('lecturas', sa.Column('contador', sa.INTEGER(), nullable=True))
    op.drop_column('lecturas', 'contador_color')
    op.drop_column('lecturas', 'contador_bn')
    op.drop_column('lecturas', 'periodo')
    op.drop_column('lecturas', 'cliente_id')
    op.drop_column('lecturas', 'contrato_id')
    op.add_column('insumos', sa.Column('tipo_insumo', sa.VARCHAR(), nullable=True))
    op.add_column('insumos', sa.Column('toner', sa.VARCHAR(), nullable=True))
    op.drop_column('facturacion', 'es_multiempresa')
    op.drop_column('facturacion', 'multiempresa')
    op.drop_column('equipos', 'contrato_id')
    op.drop_column('equipos', 'cliente_id')
    op.drop_column('equipos', 'contador_inicial_color')
    op.drop_column('equipos', 'contador_inicial_bn')
    op.add_column('contratos', sa.Column('seriedad', sa.VARCHAR(), nullable=True))
    op.drop_column('contratos', 'valor_escaneo_adicional')
    op.drop_column('contratos', 'escaneos_incluidos')
    op.drop_column('contratos', 'valor_pagina_adicional_color')
    op.drop_column('contratos', 'valor_pagina_adicional_bn')
    op.drop_column('contratos', 'paginas_color_incluidas')
    op.drop_column('contratos', 'paginas_bn_incluidas')
    op.drop_column('contratos', 'valor_mensual_base')
    op.drop_column('contratos', 'mantenimiento')
    op.drop_column('contratos', 'equipo_id')
    op.drop_column('contratos', 'poliza_seriedad')
    op.drop_column('contratos', 'poliza_contrato')
    op.create_table('polizas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seriedad', sa.VARCHAR(), nullable=True),
    sa.Column('contrato', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polizas_id'), 'polizas', ['id'], unique=False)
    op.create_table('valor_facturado',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('facturado', sa.FLOAT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valor_facturado_id'), 'valor_facturado', ['id'], unique=False)
    op.create_table('mantenimiento_correctivo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipo_id', sa.INTEGER(), nullable=True),
    sa.Column('prioridad', sa.VARCHAR(), nullable=True),
    sa.Column('requiere_equipo_respaldo', sa.VARCHAR(), nullable=True),
    sa.Column('estado_caso', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_mantenimiento', sa.DATETIME(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimiento_correctivo_id'), 'mantenimiento_correctivo', ['id'], unique=False)
    op.create_table('mantenimiento_preventivo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipo_id', sa.INTEGER(), nullable=True),
    sa.Column('tipo_mantenimiento', sa.VARCHAR(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_programada', sa.DATETIME(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimiento_preventivo_id'), 'mantenimiento_preventivo', ['id'], unique=False)
    op.create_table('mano_obra',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('pago', sa.FLOAT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mano_obra_id'), 'mano_obra', ['id'], unique=False)
    op.create_table('impuestos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('municipal', sa.FLOAT(), nullable=True),
    sa.Column('departamental', sa.FLOAT(), nullable=True),
    sa.Column('pro_deporte', sa.FLOAT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impuestos_id'), 'impuestos', ['id'], unique=False)
    op.create_table('modelos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('modelo', sa.VARCHAR(), nullable=True),
    sa.Column('toner', sa.VARCHAR(), nullable=True),
    sa.Column('rend_orig', sa.FLOAT(), nullable=True),
    sa.Column('rend_gen', sa.FLOAT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_id'), 'modelos', ['id'], unique=False)
    op.drop_index(op.f('ix_mantenimientos_preventivos_id'), table_name='mantenimientos_preventivos')
    op.drop_table('mantenimientos_preventivos')
    op.drop_index(op.f('ix_historial_id'), table_name='historial')
    op.drop_table('historial')
    # ### end Alembic commands ###
